= Anypont Connector Configuration Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Since a connector is a component in a Mule app, you should understand how to configure a Mule app before you try to configure a connector.

== Connector Configuration Requirements

Every connector has specific configuration requirements, which are described in the Reference Guide for that connector. Although connectors have different configuration requirements, most connector configurations require that you configure:

* An input source to start the app flow
* The authorization credentials needed to connect to the connector's data source. Most connectors use the Basic (username and password), OAuth, or OAuth2 authentication schemes.
* A connector operation to perform the desired action

=== Configure an Input Source

To configure an input source for a connector, select an input source associated with the connector you are configuring, or select an HTTP Listener or Scheduler. Not all connectors have associated input sources.

For more information about input sources, see <<introduction/introduction-to-anypoint-connectors.adoc#input-sources, Input Sources>>.

To see if the connector you are working with as its own input sources, see the Reference Guide for that connector.

=== Configure Authorization Credentials

To configure authorization credentials for a connector, it is recommended that you create a global element. For some connectors, configuring a global element is mandatory.

Global elements act as reusable objects. When you configure a global element for a connector, other instances of that connector in the app can share that global element.

For more information about global elements, see xxx.

=== Configure a Connector Operation

== Best Practices for Configuring Connectors

The following best practices apply to configuring connectors:

* Use a global element to define configuration details that can be shared with other instances of the connector in the flow.
* Use a properties file to store configuration variables.
* Configure a reconnection strategy to set the number of reconnection attempts to try after an initial failure.

[[global-element]]
=== Use a Global Element









[[properties-file]]

=== Use a Properties File

[[reconnection-strategy]]
=== Configure a Reconnection Strategy

When a Mule app starts, a connectivity test runs on connectors that must connect to an external server. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app, instead of blocking the deployment.

You can modify this behavior by setting the number of reconnection attempts to try after an initial failure and forcing the deployment to fail when all connection attempts fail.

* Fail Deployment forces the deployment to fail if the connection fails and any configured reconnection attempts are exhausted.

* Reconnect limits the number of reconnection attempts and the interval at which to execute them. For example, you configuration set a count of 5 reconnection attempts at a frequency of every 4000 milliseconds (ms). The reconnection strategy defaults to 2 reconnection attempts at a frequency of 2000 ms.



== See Also
